name: sprawozdanie
on: push
jobs:
  pdf:
    runs-on: ubuntu-22.04
    steps:
      - name: instalacje TeX Live
        run: sudo apt-get install -y texlive-xetex 
      - name: instalacje innych potrzebnych
        run: sudo apt-get install pandoc inkscape
      - name: instalacja python
        run: python -m pip install --upgrade pip
      - name: instalacja bibliotek
        run: pip install ipykernel scipy pint open_atmos_jupyter_utils matplotlib nbconvert
      - name: dodanie plikow z repozytorium
        uses: actions/checkout@v4
      - name: uruchumienie notebooka
        run: python -m nbconvert --to pdf --execute lab1.ipynb
      - name: pobieranie artefaktu
        uses: actions/upload-artifact@v4
        with:
          name: sprawozdanie-pdf
          path: lab1.pdf